"""criacao das tabelas iniciais

Revision ID: 121d524170aa
Revises: 
Create Date: 2026-09-02 10:16:56.241647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '121d524170aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tipo_pessoa', sa.String(length=2), nullable=False),
    sa.Column('nome_razao_social', sa.String(length=200), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=200), nullable=True),
    sa.Column('cpf_cnpj', sa.String(length=14), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('inscricao_estadual', sa.String(length=30), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('logradouro', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_cnpj')
    )
    op.create_table('marcas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', name='uq_marcas_nome')
    )
    op.create_table('portes_veiculo',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('ordem', sa.SmallInteger(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', name='uq_portes_veiculo_nome')
    )
    op.create_table('modelos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('marca_id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marca_id', 'nome', name='uq_modelos_marca_nome')
    )
    op.create_table('veiculos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.BigInteger(), nullable=False),
    sa.Column('modelo_id', sa.BigInteger(), nullable=False),
    sa.Column('porte_id', sa.BigInteger(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('cor', sa.String(length=50), nullable=False),
    sa.Column('ano_fabricacao', sa.SmallInteger(), nullable=True),
    sa.Column('ano_modelo', sa.SmallInteger(), nullable=True),
    sa.Column('renavam', sa.String(length=11), nullable=True),
    sa.Column('chassi', sa.String(length=17), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['porte_id'], ['portes_veiculo.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('veiculos')
    op.drop_table('modelos')
    op.drop_table('portes_veiculo')
    op.drop_table('marcas')
    op.drop_table('clientes')
    # ### end Alembic commands ###
