"""criacao da ordem de servico

Revision ID: 30dfc11c2170
Revises: 121d524170aa
Create Date: 2026-09-02 10:36:49.658405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30dfc11c2170'
down_revision: Union[str, Sequence[str], None] = '121d524170aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordens_servico',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.BigInteger(), nullable=False),
    sa.Column('veiculo_id', sa.BigInteger(), nullable=False),
    sa.Column('data_agendamento', sa.DateTime(), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('desconto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordens_servico')
    # ### end Alembic commands ###
