"""criacao dos precos dos servicos

Revision ID: 3c6c8887f97d
Revises: 4c77210e468f
Create Date: 2026-09-03 11:17:53.204867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c6c8887f97d'
down_revision: Union[str, Sequence[str], None] = '4c77210e468f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('precos_servicos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('servico_id', sa.BigInteger(), nullable=False),
    sa.Column('porte_id', sa.BigInteger(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['porte_id'], ['portes_veiculo.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('servico_id', 'porte_id', name='uq_precos_servicos_servico_porte')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('precos_servicos')
    # ### end Alembic commands ###
