"""criacao dos itens da ordem de servico

Revision ID: e520aab6e2e0
Revises: 3407df946f6e
Create Date: 2026-09-02 11:17:12.356609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e520aab6e2e0'
down_revision: Union[str, Sequence[str], None] = '3407df946f6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itens_ordem_servico',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ordem_servico_id', sa.BigInteger(), nullable=False),
    sa.Column('servico_id', sa.BigInteger(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('desconto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordens_servico.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_ordem_servico')
    # ### end Alembic commands ###
